// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: email/v1/email.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty" v:"required|email"`                  // v:required|email
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty" v:"required|min-length:1"` // v:required|min-length:1
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty" v:"required|min-length:1"`       // v:required|min-length:1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	mi := &file_email_v1_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_email_v1_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_email_v1_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendEmailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"Indicates if the email was sent successfully"` // Indicates if the email was sent successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" dc:"Additional message or error description"`       // Additional message or error description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRes) Reset() {
	*x = SendEmailRes{}
	mi := &file_email_v1_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRes) ProtoMessage() {}

func (x *SendEmailRes) ProtoReflect() protoreflect.Message {
	mi := &file_email_v1_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRes.ProtoReflect.Descriptor instead.
func (*SendEmailRes) Descriptor() ([]byte, []int) {
	return file_email_v1_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_email_v1_email_proto protoreflect.FileDescriptor

const file_email_v1_email_proto_rawDesc = "" +
	"\n" +
	"\x14email/v1/email.proto\x12\bemail.v1\"L\n" +
	"\fSendEmailReq\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"B\n" +
	"\fSendEmailRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2F\n" +
	"\x05Email\x12=\n" +
	"\tSendEmail\x12\x16.email.v1.SendEmailReq\x1a\x16.email.v1.SendEmailRes\"\x00B Z\x1eproxima/app/email/api/email/v1b\x06proto3"

var (
	file_email_v1_email_proto_rawDescOnce sync.Once
	file_email_v1_email_proto_rawDescData []byte
)

func file_email_v1_email_proto_rawDescGZIP() []byte {
	file_email_v1_email_proto_rawDescOnce.Do(func() {
		file_email_v1_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_v1_email_proto_rawDesc), len(file_email_v1_email_proto_rawDesc)))
	})
	return file_email_v1_email_proto_rawDescData
}

var file_email_v1_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_v1_email_proto_goTypes = []any{
	(*SendEmailReq)(nil), // 0: email.v1.SendEmailReq
	(*SendEmailRes)(nil), // 1: email.v1.SendEmailRes
}
var file_email_v1_email_proto_depIdxs = []int32{
	0, // 0: email.v1.Email.SendEmail:input_type -> email.v1.SendEmailReq
	1, // 1: email.v1.Email.SendEmail:output_type -> email.v1.SendEmailRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_v1_email_proto_init() }
func file_email_v1_email_proto_init() {
	if File_email_v1_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_v1_email_proto_rawDesc), len(file_email_v1_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_v1_email_proto_goTypes,
		DependencyIndexes: file_email_v1_email_proto_depIdxs,
		MessageInfos:      file_email_v1_email_proto_msgTypes,
	}.Build()
	File_email_v1_email_proto = out.File
	file_email_v1_email_proto_goTypes = nil
	file_email_v1_email_proto_depIdxs = nil
}
